# default server port
server:
    port: 8081

# logging configurations
logging:
    level: DEBUG
    file: global-demo.log

# eureka configuration
spring.application.name: pricing_server

eureka:   
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
            